#!/usr/bin/env bash
# Writes a Kalibr camera-IMU result into the OpenVINS config used by 07_start_vio.sh.
#   ./08_install_openvins_config.sh [imu_bag_name]     (default: newest results/imu_*)
# Reads:  results/<imu_bag>/<imu_bag>-camchain-imucam.yaml, results/<imu_bag>/<imu_bag>-imu.yaml
# Writes: ${OV_CONFIG_DIR}/kalibr_imucam_chain.yaml, kalibr_imu_chain.yaml
#         (estimator_config.yaml there is hand-tuned and left untouched)
set -euo pipefail
source "$(dirname "$0")/common.sh"

if [[ $# -ge 1 ]]; then
    IMU_BAG=$(basename "$1" .bag)
else
    IMU_BAG=$(ls -1d "${RESULTS_DIR}"/imu_* 2>/dev/null | sort | tail -1 | xargs -r basename)
    [[ -n "${IMU_BAG}" ]] || { echo "no results/imu_* found -- run 06_calib_cam_imu.sh first" >&2; exit 1; }
fi
SRC="${RESULTS_DIR}/${IMU_BAG}"
for f in "${SRC}/${IMU_BAG}-camchain-imucam.yaml" "${SRC}/${IMU_BAG}-imu.yaml"; do
    [[ -f "${f}" ]] || { echo "missing ${f}" >&2; exit 1; }
done
[[ -f "${OV_CONFIG_DIR}/estimator_config.yaml" ]] || { echo "missing ${OV_CONFIG_DIR}/estimator_config.yaml" >&2; exit 1; }

python3 - "${SRC}" "${IMU_BAG}" "${OV_CONFIG_DIR}" "${OV_IMU_NOISE_SCALE}" <<'EOF'
import sys, yaml
src, name, out = sys.argv[1:4]
scale = float(sys.argv[4])
header = f"%YAML:1.0\n# Generated by D435-Calibration/08_install_openvins_config.sh from results/{name}/ -- do not edit by hand.\n\n"

def mat(rows):
    return "".join(f"    - [{', '.join(repr(float(v)) for v in r)}]\n" for r in rows)

def vec(v):
    return "[" + ", ".join(repr(float(x)) for x in v) + "]"

# Camera chain: Kalibr's camchain-imucam is OpenVINS's kalibr_imucam_chain format;
# OpenCV's FileStorage only needs the %YAML:1.0 header.
chain = yaml.safe_load(open(f"{src}/{name}-camchain-imucam.yaml"))
body = ""
for cam in sorted(chain):
    c = chain[cam]
    body += f"{cam}:\n  T_cam_imu:\n{mat(c['T_cam_imu'])}"
    if "T_cn_cnm1" in c:
        body += f"  T_cn_cnm1:\n{mat(c['T_cn_cnm1'])}"
    body += (f"  cam_overlaps: {c.get('cam_overlaps', [])}\n"
             f"  camera_model: {c['camera_model']}\n"
             f"  distortion_coeffs: {vec(c['distortion_coeffs'])}\n"
             f"  distortion_model: {c['distortion_model']}\n"
             f"  intrinsics: {vec(c['intrinsics'])}\n"
             f"  resolution: {c['resolution']}\n"
             f"  rostopic: {c['rostopic']}\n"
             f"  timeshift_cam_imu: {float(c['timeshift_cam_imu'])!r}\n")
open(f"{out}/kalibr_imucam_chain.yaml", "w").write(header + body)

# IMU: Kalibr was run with --imu-models calibrated (PX4 applies its own accel/gyro
# calibration), so the intrinsic matrices stay identity. Noise is inflated by OV_IMU_NOISE_SCALE (common.sh).
imu = yaml.safe_load(open(f"{src}/{name}-imu.yaml"))["imu0"]
for k in ("accelerometer_noise_density", "accelerometer_random_walk", "gyroscope_noise_density", "gyroscope_random_walk"):
    imu[k] = float(imu[k]) * scale
I3 = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
body = (f"imu0:\n  T_i_b:\n{mat(imu['T_i_b'])}"
        f"  accelerometer_noise_density: {float(imu['accelerometer_noise_density'])!r}\n"
        f"  accelerometer_random_walk: {float(imu['accelerometer_random_walk'])!r}\n"
        f"  gyroscope_noise_density: {float(imu['gyroscope_noise_density'])!r}\n"
        f"  gyroscope_random_walk: {float(imu['gyroscope_random_walk'])!r}\n"
        f"  rostopic: {imu['rostopic']}\n"
        f"  time_offset: {float(imu.get('time_offset', 0.0))!r}\n"
        f"  update_rate: {float(imu['update_rate'])!r}\n"
        f"  model: \"kalibr\"\n"
        + "".join(f"  {k}:\n{mat(I3)}" for k in ("Tw", "R_IMUtoGYRO", "Ta", "R_IMUtoACC"))
        + f"  Tg:\n{mat([[0, 0, 0]] * 3)}")
open(f"{out}/kalibr_imu_chain.yaml", "w").write(header + body)
EOF

echo "${IMU_BAG}" >"${OV_CONFIG_DIR}/CALIBRATION_SOURCE"
echo "OpenVINS config updated from results/${IMU_BAG}/ -> ${OV_CONFIG_DIR}/ (IMU noise x${OV_IMU_NOISE_SCALE})"
grep -E "rostopic|timeshift|noise_density|random_walk" "${OV_CONFIG_DIR}"/kalibr_*_chain.yaml | sed 's/^/  /'
echo "Next: ./07_start_vio.sh"
